export const EXAM_STATUSES = ["DRAFT", "PUBLISHED", "ARCHIVED"] as const;
export const ANSWER_CHOICES = ["A", "B", "C", "D"] as const;
export const EXAM_RESULT_STATUSES = ["NOT_TAKEN", "PASSED", "FAILED"] as const;
export const APPROVAL_STATUSES = [
  "DRAFT",
  "WAITING_APPROVAL",
  "APPROVED",
  "REJECTED",
  "CANCELLED"
] as const;
export const CERTIFICATE_STATUSES = ["NOT_ISSUED", "ACTIVE", "EXPIRED", "REVOKED"] as const;

export const HISTORY_TARGET_TYPES = [
  "INSPECTOR",
  "EXAM",
  "EXAM_QUESTION",
  "EXAM_RESULT",
  "EXAM_RESULT_ANSWER",
  "APPROVAL_REQUEST",
  "CERTIFICATE_RESULT"
] as const;

export const HISTORY_ACTIONS = [
  "CREATE_INSPECTOR",
  "UPDATE_INSPECTOR",
  "DEACTIVATE_INSPECTOR",
  "CREATE_EXAM",
  "UPDATE_EXAM",
  "PUBLISH_EXAM",
  "ARCHIVE_EXAM",
  "IMPORT_EXAM_QUESTIONS",
  "CREATE_QUESTION",
  "UPDATE_QUESTION",
  "DELETE_QUESTION",
  "START_EXAM",
  "SUBMIT_EXAM",
  "UPDATE_EXAM_SCORE",
  "SUBMIT_APPROVAL",
  "APPROVE",
  "REJECT",
  "CANCEL_APPROVAL",
  "ISSUE_CERTIFICATE",
  "UPDATE_CERTIFICATE",
  "REVOKE_CERTIFICATE"
] as const;
